### ISSUE TITLE
Nothing happens when I click Remove Duplicate

### ISSUE THREAD

**Issue by vfailla** [eyalroz/removedupes#63] opened 2021-08-09 10:29 UTC
First of all, I want to thank you for your very useful extension, as a developer I really appreciate your effort!

Today I noticed the extension doesn't work anymore. It simply shows nothing when I try to remove the duplicates.

- Thunderbird for MacOSX ver. 78.12.0 (64 bit)
- Remove Duplicate messages ver. 0.5.2b3

Please, find attached the console log.

Let me know whether I can provide some more details.

Thank you so much.

[console-export-2021-8-9_12-19-53.txt](https://github.com/eyalroz/removedupes/files/6953661/console-export-2021-8-9_12-19-53.txt)

**Comment by eyalroz** [comment] 2021-08-09 10:33
Duplicate of #57 - and resolved by [v0.5.2b4](https://github.com/eyalroz/removedupes/releases/tag/v0.5.2b4).

**Closed by eyalroz** 2021-08-09 10:33 UTC
