### ISSUE TITLE
Version 0.5.4 Beta 1 release does not have binary

### ISSUE THREAD

**Issue by JeppeKlitgaard** [eyalroz/removedupes#172] opened 2023-07-13 22:51 UTC
I am trying to use Remove Dupes with the latest Thunderbird (115), which I understand is not supported by the latest stable Remove Dupes extension. The release notes for 0.5.4 beta 1 indicate that it has support for 115, but it does not feature a `.xpi` file.

![image](https://github.com/eyalroz/removedupes/assets/1814611/c49cf196-b113-49d7-9a13-88bc1d006d7d)

Would it be possible to upload the beta version (or alternatively cut a stable release for 115 if this is viable)?

Thank you for making this fantastically useful tool!

**Comment by eyalroz** [comment] 2023-07-13 23:09
The GitHub upload failed somehow... at any rate - beta 1 is gone, there is now a beta 2. Please try it out...

unfortunately, the toolbar button is missing, and I have not yet figured out how to get it to appear again (Mozilla people have made it difficult and haven't documented how it should be done).

**Comment by JeppeKlitgaard** [comment] 2023-07-13 23:23
Thank you for the quick reply!

Unfortunately adding the XPI file in 115 gives the following error:
![image](https://github.com/eyalroz/removedupes/assets/1814611/9c8e8ff1-ca7e-4356-a243-7448506e6172)

Perhaps there is still some metadata that needs to be updated?

**Comment by JeppeKlitgaard** [comment] 2023-07-14 00:12
I manually edited the `manifest.json` file to got it working, but nothing happens when I press Tools > Remove Duplicates. The following error appears in the error console:

```
Uncaught TypeError: messageWindow.statusFeedback is undefined
    setStatus chrome://removedupes/content/removedupes-common.js:85
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:292
```

**Comment by eyalroz** [comment] 2023-07-14 07:21
Working on it.

**Comment by eyalroz** [comment] 2023-07-14 07:30
Try a new beta:

https://github.com/eyalroz/removedupes/releases/tag/v0.5.4b3

**Comment by JeppeKlitgaard** [comment] 2023-07-14 09:12
Beta 3 can be added and fixes the version constraint issue, though I am still seeing the same error:
![image](https://github.com/eyalroz/removedupes/assets/1814611/142f758f-2e3c-442d-800b-6a07bd087262)

This happens when pressing Tools > Remove Duplicates

**Comment by eyalroz** [comment] 2023-07-14 16:04
Yes, this is effectively a dupe of #166, so closing this one and working on that one.

**Closed by eyalroz** 2023-07-14 16:04 UTC

**Comment by eyalroz** [comment] 2023-07-14 16:13
Please see the new build on #166.
