### ISSUE TITLE
Failed to move to trash

### ISSUE THREAD

**Issue by mostly-nonsense** [eyalroz/removedupes#60] opened 2021-08-01 23:22 UTC
Receiving failed moving messages error.

Failed moving messages to: 
imap://xxx%40xxx@imap.gmail.com/[Gmail]/Trash
&
mailbox://nobody@Local%20Folders/Trash

Thunderbird: 78.12.0 (32-bit)
Version: 0.5.2b2

**Comment by eyalroz** [comment] 2021-08-02 13:18
This is a dupe of #57 . Please use the build available there (0.5.2b3)

**Closed by eyalroz** 2021-08-02 13:18 UTC
