### ISSUE TITLE
Remove Duplicates Recursion Error

### ISSUE THREAD

**Issue by gjs---** [eyalroz/removedupes#28] opened 2020-11-08 22:03 UTC
'Remove Duplicate' works OK on my IMAP Inbox, and says 'No duplicates found' in several local folders.  However, it fails in two local folders.  One is named '2011' and contains 887 messages.  The other is '2009', with 197 messages.  In both cases, after about five seconds a window title appeared for about a second, saying "Mozilla Thunderbird (not responding)".  No dialog appeared.  I found the following in the error console:

```
Uncaught InternalError: too much recursion
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
removedupes.js:409:28
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    next self-hosted:1099
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
Uncaught InternalError: too much recursion
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
removedupes.js:409:28
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    next self-hosted:1099
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
Uncaught InternalError: too much recursion
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
removedupes.js:409:28
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    next self-hosted:1099
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
Uncaught InternalError: too much recursion
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
removedupes.js:409:28
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    next self-hosted:1099
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332

```

Thunderbird 78.4.1
RemoveDupes 0.5
Windows 10 Home 1903

**Comment by eyalroz** [comment] 2020-11-08 22:23
This is a duplicate of issue #26 .

**Closed by eyalroz** 2020-11-08 22:23 UTC
