### ISSUE TITLE
No response on folders with too many or too large messages

### ISSUE THREAD

**Issue by datenheim** [eyalroz/removedupes#29] opened 2020-11-13 09:57 UTC
Thunderbird 78.4.3, Plugin 0.5, several IMAP accounts

When I fire up the search for duplicates on folders containing different number of messages the plugin stops at one point to give a response at all.

The problem is not directly tied to the number of messages alone.
Some folders with ~20000 messages work, another with 12000 works not, thus content and or size of the messages seems to play a role.

I noticed after starting a dupe-search on a larger folder that Tunderbird gets unresponsive after ~5-6 seconds (windows renders the unresponsive message):

![dups](https://user-images.githubusercontent.com/101634/99059034-4ce3f380-259e-11eb-94c5-32064abab6af.PNG)

If this happens there comes no response from the plugin at all - neither mentioning "no dupes" nor the dupes dialogue.

It looks like the plugin hits a timeout and gets terminated if the search takes too long. I noticed this also in earlier versions (years ago). Because of that I switched to the _competitor_ "Remove Duplicates" plugin that was working in TB 68 for a while.

Is there a way to avoid this behaviour? Maybe by splitting the search into smaller chunks that take less time?

I got this console output:
```
Uncaught InternalError: too much recursion
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
removedupes.js:409:28
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:511
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    next self-hosted:1099
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
```
While Writing this I notice it is coupled/duplicate of #26

**Comment by eyalroz** [comment] 2020-11-13 10:09
Indeed, a dupe of #26 .

Unfortunately, this is a Thunderbird bug as I don't actually use recursion. But somebody must have messed with the implementation of timeout-setting code.

**Comment by gjs---** [comment] 2020-11-13 14:02
What happen if you try the workaround I suggested in #26?  That is, go to ``` Tools > Add-on Options > Remove Duplicate Messages ``` and turn OFF one or both of:

* [ ] Compare addresses stripped and sorted
* [ ] Author ('From')

**Comment by eyalroz** [comment] 2020-11-13 15:57
Let's continue the discussion in #26 .

**Closed** 2020-11-13 15:57 UTC
