### ISSUE TITLE
Search duplicates across all mailboxes in whole Thunderbird.

### ISSUE THREAD

**Issue by DeniR** [eyalroz/removedupes#199] opened 2023-12-20 09:19 UTC
Currently there is no option to search for duplicates across all mailboxes in whole Thunderbird.
It search only in selected mailbox and it's subfolders.

**Comment by eyalroz** [comment] 2023-12-20 22:08
Of course there is - you just need to select all of your mailboxes.

... which you used to be able to, but Thunderbird has been crippled to prevent you from doing so.

In theory, I suppose I could implement my own alternative folder selection mechanism. However, I need to find the time to work on more critical updates (see other bugs around here) - and I haven't even managed to crack the problem of putting a menubutton on the mail toolbar, since TB has crippled that possibility as well. So, keeping this bug open, but what you should really do is talk to the Thunderbird developers and ask them to re-enable multiple folder selection. 

Talk to them = File a bug and chat them up on IRC/matrix.

**Comment by PackElend** [comment] 2024-03-11 18:04
Hi,
it looks like the root cause does still exits as this issue is mentioned again in https://github.com/eyalroz/removedupes/issues/209

I would love to see that option working.
I moved emails from my main mailbox to my archive mailbox but Thunderbird only copied the messages, not deleting them in the main mailbox

**Comment by PackElend** [comment] 2024-08-09 14:22
does this thunderbird fix https://github.com/eyalroz/removedupes/ fixes that issue?

**Comment by eyalroz** [comment] 2024-08-10 16:52
So, again - not a removedupes bug, but a Thunderbird bug; closing.

However, it seems TB 128 is restoring multi-folder selection, and there's a removedupes release now which supports TB 128.

**Closed** 2024-08-10 16:53 UTC

**Comment by PackElend** [comment] 2024-08-11 12:18
I'm not sure if that can be closed until https://github.com/eyalroz/removedupes/issues/186 is closed.
