### ISSUE TITLE
no action

### ISSUE THREAD

**Issue by ergti** [eyalroz/removedupes#151] opened 2023-05-11 10:37 UTC
versions of Thunderbird = 102.11.0 (64-bit)
Windows 11 Pro
extensions = only Remove Duplicate Messages

![image](https://github.com/eyalroz/removedupes/assets/69270367/bca4ede9-cb38-4933-bc70-2695ceec6344)

Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.formatStringFromName]", result: 2147500037, filename: "chrome://removedupes/content/removedupes-common.js", lineNumber: 67, columnNumber: 0, data: null, stack: "RemoveDupes.Strings.format@chrome://removedupes/content/removedupes-common.js:67:22\nRemoveDupes.StatusBar.setNamedStatus@chrome://removedupes/content/removedupes-common.js:95:34\nRemoveDupes.MessengerOverlay.abortDupeSearch@chrome://removedupes/content/removedupes.js:115:25\nRemoveDupes.MessengerOverlay.beginSearchForDuplicateMessages@chrome://removedupes/content/removedupes.js:97:34\nRemoveDupes.MessengerOverlay.searchAndRemoveDuplicateMessages@chrome://removedupes/content/removedupes.js:56:32\noncommand@chrome://messenger/content/messenger.xhtml:1:30\n", location: XPCWrappedNative_NoHelper }
​
columnNumber: 0
​
data: null
​
filename: "chrome://removedupes/content/removedupes-common.js"
​
lineNumber: 67
​
location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, … }
​
message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.formatStringFromName]"
​
name: "NS_ERROR_FAILURE"
​
result: 2147500037
​
stack: "RemoveDupes.Strings.format@chrome://removedupes/content/removedupes-common.js:67:22\nRemoveDupes.StatusBar.setNamedStatus@chrome://removedupes/content/removedupes-common.js:95:34\nRemoveDupes.MessengerOverlay.abortDupeSearch@chrome://removedupes/content/removedupes.js:115:25\nRemoveDupes.MessengerOverlay.beginSearchForDuplicateMessages@chrome://removedupes/content/removedupes.js:97:34\nRemoveDupes.MessengerOverlay.searchAndRemoveDuplicateMessages@chrome://removedupes/content/removedupes.js:56:32\noncommand@chrome://messenger/content/messenger.xhtml:1:30\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
[removedupes-common.js:67](chrome://removedupes/content/removedupes-common.js)
    format chrome://removedupes/content/removedupes-common.js:67
    setNamedStatus chrome://removedupes/content/removedupes-common.js:95
    abortDupeSearch chrome://removedupes/content/removedupes.js:115
    beginSearchForDuplicateMessages chrome://removedupes/content/removedupes.js:97
    searchAndRemoveDuplicateMessages chrome://removedupes/content/removedupes.js:56
    oncommand chrome://messenger/content/messenger.xhtml:1

**Comment by eyalroz** [comment] 2023-05-16 18:50
First, please try [v0.5.3.2](https://github.com/eyalroz/removedupes/releases/tag/v0.5.3.2).

Second - what is your locale? What language and countrey are you using TB with?

**Comment by noel-lapin** [comment] 2023-05-16 21:07
This is my personal narrow experience, only for info.

1. When there is a duplicate message, the debug console reports nothing.
2. When there is no duplicate, the console shows below:
Uncaught TypeError: RemoveDupes.MessengerOverlay.setStatus is not a function
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:304
3.In earlier versions of this add-on, when there is no duplicate, it pops up an dialog. But this version shows no pop-up nor any message. So usually I think "Oh, there is no duplicate, because nothing happens."
 
Thunderbird 102.11.0 (64-bit)
Windows 10 HOME, 22H2, 19045.2965

used locale when installed Windows and Thunderbird: en_US
using settings about language -
Windows display, apps & websites, regional format, speech: en_US
keyboard: ja_JP
language for non-Unicode programs: ja_JP

I don't install Node.js. However, I see in Task Manager, some add-on runs a thread titled like "Node.js server side script". I don't know what this has to do with the present problem.

**Comment by noel-lapin** [comment] 2023-05-16 21:21
This is my personal narrow experience, only for info.
(1) When there is a duplicate message, the debug console reports nothing.
(2) When there is no duplicate, the console shows below:
```
Uncaught TypeError: RemoveDupes.MessengerOverlay.setStatus is not a function
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:304
```
(3)In earlier versions of this add-on, when there is no duplicate, it pops up an dialog. But this version shows no pop-up nor any message. So usually I think "Oh, there is no duplicate, because nothing happens."
 
Thunderbird 102.11.0 (64-bit)
Windows 10 HOME, 22H2, 19045.2965

used locale when installed Windows and Thunderbird: en_US
using settings about language -
Windows display, apps & websites, regional format, speech: en_US
keyboard: ja_JP
language for non-Unicode programs: ja_JP

I don't install Node.js. However, I see in Task Manager, some add-on runs a thread titled like "Node.js server side script". I don't know what this has to do with the present problem.

**Comment by eyalroz** [comment] 2023-05-16 21:23
Dupe of #150 . Please try [0.5.3.2](https://github.com/eyalroz/removedupes/releases/tag/v0.5.3.2).

**Comment by noel-lapin** [comment] 2023-05-17 20:14
The problem solved! No output to the Error Console. And when there is no duplicate, the message dialog pops up as before.
Thanks very much!

**Comment by eyalroz** [comment] 2023-05-17 20:34
Sorry for not noticing this before. Unfortunately, I don't have a group of "beta-testers", and there's no beta release channel on ATN, and this is the result :-(

**Closed** 2023-06-02 21:18 UTC
