### ISSUE TITLE
Provide auto run on Thunderbird start

### ISSUE THREAD

**Issue by shumashv1** [eyalroz/removedupes#217] opened 2024-06-10 12:18 UTC

**Comment by eyalroz** [comment] 2024-09-02 09:56
Mostly a duplicate of #197 .

If you just mean scanning all messages automatically on app start - I will not do that, because:

1. After you've done that once, it does not make sense to re-scan all your messages on the next app start. You would just find the same things you left last time.
2. It is too much of a danger of accidental data loss.

**Closed by eyalroz** 2024-09-02 09:56 UTC
