### ISSUE TITLE
Will RDM result in building *all* the .msf files? That's what I want to do.

### ISSUE THREAD

**Issue by jaysmithgit** [eyalroz/removedupes#49] opened 2021-05-04 02:24 UTC
Hi...  

I tried to send an email to the link you provided  but it bounced.  That address is on:
https://github.com/eyalroz/removedupes/

We are using TB 78.7.1 on Kubuntu Linux 20.04.  (We have been using Thunderbird for at least 15 years and have always been trying to solve this problem, but as of a couple months ago we made a big jump to new workstations with new Thunderbird and so I would really like to find an answer to this as I have to otherwise *manually* "walk" through the entire IMAP directory structure for *each* seat!)

We have a directory structure probably up to 12 levels deep in some places and, in total, containing many tens of thousands of emails.

I am *NOT* concerned about finding or removing duplicate emails.

I only want to build .msf files.  But...

I found a years-old search result saying that a then-existing (but not now?) "find-duplicates" add-on would, as a by-product of the process, build all the .msf files in the user's TB profile, including for a new TB installation.

On our system, the "/public" files are on our IMAP server and each user's Thunderbird profile contains only .msf files.

We need all the .msf files to be present in each person's TB profile so that other add-ons, such as Nostalgy++ or QuickFolders, can "see" the directory structure and mailbox file *names* and thus can file into those mailboxes.

I have not been able to find any Thunderbird *automated* method to build all the .msf files.  The only method I have found is to manually use the GUI to "open" each folder and thus expose the mailboxes -- which then causes Thunderbird to create the .msf files.

So, I am wondering... in the process of doing its job, does your program create .msf files for the entire IMAP structure?

(I don't care about message counts of the files IN the mailboxes.  I just want the .msf files to be created FOR Each mailbox.)

Thanks,

Jay Smith

**Comment by eyalroz** [comment] 2021-05-04 20:15
Hello Jay,

My email changed a few months ago - I need to make sure it's updated everywhere I have the old email mentioned. Sorry about that.

Also, and sadly, it seems that removedupes does not trigger msf creation when an msf is missing; at least, not always.

However - I've just tested what happens when I click any IMAP folder in an account with no MSF's, and all the MSFs got generated - not just the one for the folder I clicked, nor even just the ones on the path from the root folder to it. So maybe you don't need any extension at all?

Anyway, another thing to try is the <kbd>File</kbd> | <kbd>Compact Folders</kbd> menu item.  That might do .msf rebuilding as well.

Closing, since this is not a bug, but you may comment further if you like.

**Closed by eyalroz** 2021-05-04 20:15 UTC

**Comment by jaysmithgit** [comment] 2021-05-05 00:35
Hi, Thanks for your quick reply.

In my system, the .msf files are definitely not being created, down in the IMAP /public part of the structure, for more than the specific folders that are clicked or opened/exposed by opening a folder that contains folders. 

Perhaps that is due to the size of structure, but it is not even trying and then stopping.  It only creates .msf if the user causes it to happen in the GUI and only for what the user can physically see in the GUI.

I had thought about trying "File, Compact", but I have been wary of doing so. Before we migrated from a very old (6 years old?) Thunderbird up to 78.7.1, if I tried to do "File, Compact", it would run for a couple hours (making Thunderbird unusable during that time because it was so slow) and then it would silently die.  I have been hesitant to try it again, but I guess I need to take the risk.  It's not so much of a risk on a new seat install where I don't have a lot of labor/time to lose.

If this "create MSF files" function is something you would like to create, I would use it.

**Comment by eyalroz** [comment] 2021-05-05 14:06
@jaysmithgit : I'm not sure there's a specific explicit capability of triggering that. After all, MSF's are an implementation detail for one kind of message storage format.

But if something happens on that front, I'll comment here and let you know.
