### ISSUE TITLE
getByName() fails with 0.5.2b2 and 0.5.2b3

### ISSUE THREAD

**Issue by bbooyydd** [eyalroz/removedupes#59] opened 2021-07-29 02:48 UTC
Change to v0.5.2b2 caused RDM to stop working.  Right click "Remove Duplicates ..." link exists in context menu, but pop up list to confirm does not happen.  Reverting to v0.5 it works as before.   TB 78.12.0 windows 10

**Comment by eyalroz** [comment] 2021-07-29 07:10
@bbooyydd : Please have a look at #57 and let me know if the new build there fixes the problem.

**Comment by bbooyydd** [comment] 2021-07-29 16:47
v0.5.2b3 installed but there was no difference.  I get no error messages.  The review popup does not happen.  If I turn off the review it makes no difference.  No duplicates are removed in either case.  I'll stay with 0.5 for now with no auto updates, and will check back here in a few days.

**Comment by eyalroz** [comment] 2021-07-29 18:52
@bbooyydd
Can you please list any errors you got in the error console with v0.5.2b3?

Also - note that the addons.thunderbird.net update mechanism is broken, in the sense that beta versions are treated just like regular versions pushed to all users :-(

**Comment by bbooyydd** [comment] 2021-07-29 20:01
I reinstalled b3, then restarted TB.  The only action I did was clicking "Remove Duplicates ..," on one folder.  The error log during that time is pasted below.  removeddupes is mentioned in the 12:55:10.642 entry.
=====================
12:54:59.065
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
12:54:59.240 Successfully loaded OpenPGP library rnp.dll version 0.14+git20210121.7c8492b4.MZLA from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll RNPLib.jsm:95:15
12:54:59.258
Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:570
12:54:59.259 1627588499258	addons.xpi	WARN	Exception running bootstrap method startup on twitter@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:570:20) JS Stack trace: readJSON/</<@Extension.jsm:570:20
onStopRequest@NetUtil.jsm:128:18
12:54:59.389 Found 0 public keys and 0 secret keys (0 protected, 0 unprotected) RNPLib.jsm:291:15
12:54:59.394
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
12:54:59.860
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
12:55:00.094
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
12:55:00.095
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
12:55:00.486 1627588500486	tbsortfolders.folderPane	DEBUG	Init
12:55:00.487 1627588500486	tbsortfolders.folderPane	DEBUG	Add observer
12:55:00.898 Trying to load C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:51:11
12:55:00.901 Successfully loaded OTR library C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:59:13
12:55:01.282 Uncaught (in promise) 
Exception { name: "NS_ERROR_ILLEGAL_VALUE", message: "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMessenger.msgHdrFromURI]", result: 2147942487, filename: "chrome://messenger/content/mailTabs.js", lineNumber: 419, columnNumber: 0, data: null, stack: "restoreTab@chrome://messenger/content/mailTabs.js:419:32\nrestoreTab@chrome://messenger/content/tabmail.js:1574:19\nrestoreTabs@chrome://messenger/content/tabmail.js:1595:19\natStartupRestoreTabs@chrome://messenger/content/msgMail3PaneWindow.js:1096:13\n", location: XPCWrappedNative_NoHelper }
mailTabs.js:419
12:55:10.642
Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]", result: 2147500037, filename: "chrome://removedupes/content/removedupes-common.js", lineNumber: 135, columnNumber: 0, data: null, stack: "getByName@chrome://removedupes/content/removedupes-common.js:135:24\nRemoveDupes.namedAlert@chrome://removedupes/content/removedupes-common.js:119:34\ntraverseSearchFolderSubfolders@chrome://removedupes/content/removedupes.js:232:21\naddSearchFolders@chrome://removedupes/content/removedupes.js:215:34\nbeginSearchForDuplicateMessages@chrome://removedupes/content/removedupes.js:115:36\nsearchAndRemoveDuplicateMessages@chrome://removedupes/content/removedupes.js:79:34\noncommand@chrome://messenger/content/messenger.xhtml:1:30\n", location: XPCWrappedNative_NoHelper }
removedupes-common.js:135

​

**Comment by eyalroz** [comment] 2021-07-29 20:23
So, it looks like there's something wrong with the localization registry. But it's a weird error ...  I don't know what to say.

Tell me, though, which locale are you using? Which language is your Thunderbird interface in?

**Comment by eyalroz** [comment] 2021-08-06 13:44
Please try the new version here:

https://github.com/eyalroz/removedupes/releases/tag/v0.5.2b4

(or just get the XPI directly: 
[removedupes_0.5.2b4_tbird.xpi.zip](https://github.com/eyalroz/removedupes/files/6945906/removedupes_0.5.2b4_tbird.xpi.zip)
)

**Comment by eyalroz** [comment] 2021-08-09 10:34
Ok, this is a dupe of #57  - and indeed resolved by v0.5.2b4.

**Closed by eyalroz** 2021-08-09 10:34 UTC
