### ISSUE TITLE
0.5.4b3 - remove duplicate is missing from context menu

### ISSUE THREAD

**Issue by xyxzxyz** [eyalroz/removedupes#178] opened 2023-07-14 18:20 UTC
I just installed 0.5.4B3 on v115, 'Remove duplicate' is now missing from context menu...?

**Comment by eyalroz** [comment] 2023-07-14 21:29
Yes, it is missing from the context menu. The TB people made significant changes to the main messenger window, and have failed to explain how we need to change the way we add to the context menu :-(  ; they only listed directions for crippled extensions ("WebExtensions").

**Comment by eyalroz** [comment] 2023-07-15 09:31
Dupe of bug #163.

**Closed by eyalroz** 2023-07-15 09:31 UTC
