### ISSUE TITLE
Addon stops working after sometime

### ISSUE THREAD

**Issue by kapukus** [eyalroz/removedupes#61] opened 2021-08-04 08:09 UTC
Hi, The Remove Dup add-on stops working after sometime - after the setting comes.

I am using Thunderbird 78.12.0 (64-bit) and Remove Dup (0.5.2b3) by Eyal Rozenberg. When I reinstall it, it works for sometime. Then the 'settings' option comes (spanner) and it still shows in the right click menu but doesnt do anything, doesnt give any error.

**Comment by ngu-cadreparis** [comment] 2021-08-04 10:58
Same here

**Comment by eyalroz** [comment] 2021-08-04 10:59
I'm not sure what you mean by "Then the 'settings' option comes (spanner)."

Are you getting anything in the Error Console?

**Comment by kapukus** [comment] 2021-08-05 11:33
Hi,

Thanks for the help.

Not sure where the Error Console is - is this something in Thunderbird?

What I meant by the statement - when I install the add-on, the settings dont show for sometime - I think it works till that happens. Then the settings start showing (the spanner gets visible) and it stops working (no error).

[cid:3b068889-e931-44de-91a9-5a70b89cbb9a]

Thanks


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ngu-cadreparis** [comment] 2021-08-05 13:22
Here's what I get in the error console :

Uncaught
Exception
​columnNumber: 0
​data: null
​filename: "chrome://removedupes/content/removedupes-common.js"
​lineNumber: 135
​location: XPCWrappedNative_NoHelper
​​QueryInterface: QueryInterface()
​​​length: 1
​​​name: "QueryInterface"
​​​<prototype>: ()
​​​​apply: function apply()
​​​​arguments:
​​​​bind: function bind()
​​​​call: function call()
​​​​caller:
​​​​constructor: function Function()
​​​​length: 0
​​​​name: ""
​​​​toSource: function toSource()
​​​​toString: function toString()
​​​​Symbol(Symbol.hasInstance): function Symbol.hasInstance()
​​​​<get arguments()>: function arguments()
​​​​<set arguments()>: function arguments()
​​​​<get caller()>: function caller()
​​​​<set caller()>: function caller()
​​​​<prototype>: Object { … }
​​asyncCaller: null
​​asyncCause: null
​​caller: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), 
filename: , name: , … }
​​columnNumber: 24
​​filename: "chrome://removedupes/content/removedupes-common.js"
​​formattedStack: 
***@***.******@***.******@***.******@***.******@***.******@***.******@***.***://messenger/content/messenger.xhtml:1:30\n"
​​lineNumber: 135
​​name: "getByName"
​​nativeSavedFrame: SavedFrame { source: 
"chrome://removedupes/content/removedupes-common.js", sourceId: 610, 
line: 135, … }
​​sourceId: 610
​​sourceLine: ""
​​toString: function toString()
​​<get asyncCaller()>: function asyncCaller()
​​<get asyncCause()>: function asyncCause()
​​<get caller()>: function caller()
​​<get columnNumber()>: function columnNumber()
​​<get filename()>: function filename()
​​<get formattedStack()>: function formattedStack()
​​<get lineNumber()>: function lineNumber()
​​<get name()>: function name()
​​<get nativeSavedFrame()>: function nativeSavedFrame()
​​<get sourceId()>: function sourceId()
​​<get sourceLine()>: function sourceLine()
​​<prototype>: Object { … }
​message: "Component returned failure code: 0x80004005 
(NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]"
​name: "NS_ERROR_FAILURE"
​result: 2147500037
​stack: 
***@***.******@***.******@***.******@***.******@***.******@***.******@***.***://messenger/content/messenger.xhtml:1:30\n"
​<prototype>: ExceptionPrototype
​​columnNumber:
​​data:
​​filename:
​​lineNumber:
​​location:
​​message:
​​name:
​​result:
​​stack:
​​toString: function toString()
​​Symbol(Symbol.toStringTag): "Exception"
​​<get columnNumber()>: function columnNumber()
​​<get data()>: function data()
​​<get filename()>: function filename()
​​<get lineNumber()>: function lineNumber()
​​<get location()>: function location()
​​<get message()>: function message()
​​<get name()>: function name()
​​<get result()>: function result()
​​<get stack()>: function stack()
​​<set stack()>: function stack()
​​<prototype>: Object { … }
removedupes-common.js:135

**Comment by eyalroz** [comment] 2021-08-05 13:28
So, it's a duplicate of #58. I hope to find time this weekend to fix this (if I can reproduce it... :-( )

**Closed by eyalroz** 2021-08-05 13:28 UTC

**Comment by kapukus** [comment] 2021-08-06 06:42
Thanks Eyal. Good Luck and Happy Hunting 🙂


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by eyalroz** [comment] 2021-08-06 13:43
Please try this new version. It doesn't specifically address what you've seen, but there's a good chance it'll fix things:

https://github.com/eyalroz/removedupes/releases/tag/v0.5.2b4

**Comment by ngu-cadreparis** [comment] 2021-08-06 13:45
Works great! Thank you

**Comment by eyalroz** [comment] 2021-08-06 14:05
Sorry about this, it was a really dumb oversight on my part, a line of code which snuck into the beta by mistake.

**Comment by kapukus** [comment] 2021-08-06 14:55
Hi,

Want to try this version but I am a novice & not a developer.

How do I download this release and enable in Thunderbird or do I have to wait for release on Thunderbird (I think the current release is v0.5 2b2).


Thanks

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by eyalroz** [comment] 2021-08-06 17:16
@kapukus : 

1. Follow the link.
2. At that page, there's an XPI file as an "asset"; save it to disk
3. In Thunderbird, go to Tools | Add-Ons
4. In the Add-Ons tab, click the gear-wheel menu-button.
5. Choose Install from Disk
6. Locate and select the file you downloaded
7. Accept the installation in the dialog which comes up

Also, the current release is 0.5.1 ; but, unfortunately, the add-ons site doesn't distinguish between beta and release versions.
